### ISSUE TITLE
To import this code to new project it shows error.

### ISSUE THREAD

**Issue by Saravana181187** [watsonbox/ios_google_places_autocomplete#1]
gpaViewController.placeDelegate = self

In this line i have error   "type viewcontroller does not conform to protocol googleplacesautocompletedelegate".

How to fix it and what is the solution.

**Comment by Rogog** [comment]
I'm getting the same issue, support on this would be highly appreciated.

**Comment by Rogog** [comment]
You need to do the following: 

In your ViewController.swift file change the following: 

extension ViewController: GooglePlacesAutocompleteDelegate {
  func placeSelected(place: Place) {
    println(place.description)
    println(place.id)
  }

to 

extension ENTERCLASSNAMEHERE: GooglePlacesAutocompleteDelegate {
  func placeSelected(place: Place) {
    println(place.description)
    println(place.id)
  }

**Comment by Saravana181187** [comment]
It is also not Worked for me.

**Comment by Saravana181187** [comment]
Suppose can i copy the Xib into Storyboard it will work or not?
