### ISSUE TITLE
Close Button not working?

### ISSUE THREAD

**Issue by AbhiVashistha** [watsonbox/ios_google_places_autocomplete#18]
On click of close button, the same view is loaded again. I have called this view controller as a modal segue from another view controller. How can I go back to previous view controller on click of close button?
Thanks!

**Comment by watsonbox** [comment]
If you could point to some example code illustrating your problem I'll do my best to point you in the right direction.

**Comment by AbhiVashistha** [comment]
Thanks for the prompt reply. Attached image will show you my IB. In Search Screen, on click of edit button at navigation bar I want to show the screen where user will enter an address and on this view controller I am using your code. I want that on click of close button this location view controller should dismiss and search screen should appear again, but its not happening and the Google places API screen is loading again and again when i click close button. I hope you will understand better after having a look at the attached screenshots.
THe segue used between search and location screen is modal.
Thanks!
![screen shot 2015-07-15 at 1 53 36 am](https://cloud.githubusercontent.com/assets/3148946/8684250/f5cdbbee-2a94-11e5-9fc2-9c9a4de1fc12.png)
![screen shot 2015-07-15 at 1 56 31 am](https://cloud.githubusercontent.com/assets/3148946/8684254/ff76f57a-2a94-11e5-8ca2-fc1c16b88f65.png)
![screen shot 2015-07-15 at 1 56 31 am](https://cloud.githubusercontent.com/assets/3148946/8684255/0169b82c-2a95-11e5-93a2-776d2d7a1339.png)

**Comment by scottlow** [comment]
I'm running into a similar problem. I'm extremely new to iOS development, and I'm trying to figure out the "best practice" approach for incorporating the GooglePlacesAutocomplete.xib into a multistep wizard I want to create. 

I would normally have my main view controller (ViewController1) be the GooglePlacesAutocomplete delegate and pop the Autocomplete.xib from there, but given the fact that I want to create a wizard modal with place searching as one of many steps, I figured I would need a separate ViewController (ViewController2) that acts as a delegate to the Autocomplete and also manages segues for sequential steps in the wizard.  

By doing this (as @AbhiVashistha has done above), however, I'm running into an issue where two segues execute. The first occurs when transitioning from ViewController1 to ViewController2, and the second occurs when presentViewController() is called.

Any advice you have on proper architecture for a situation like this would be greatly appreciated.

**Comment by watsonbox** [comment]
@AbhiVashistha The code I used in the example just loads the `GooglePlacesAutocomplete` view in `viewDidAppear` for convenience.  However, when the user chooses a location, the previous view will 'appear' again, and so `viewDidAppear` will be called and the selector view will be re-displayed.  So I don't think this is a problem with the close button behavior.

Why don't you just get rid of your user location view all together and present the `gpaViewController` directly on the 'Edit' button handler in the search view?
