### ISSUE TITLE
Access_denied

### ISSUE THREAD

**Issue by PhaelIshall** [watsonbox/ios_google_places_autocomplete#20]
I'm geting an Access denied error from Google places, do we have to change anything other than the API key?

**Comment by swennemans** [comment]
@PhaelIshall I had the same issue, problem is probably you've set up an IOS Key and Google Places IOS api. Don't do this. 

Check: http://stackoverflow.com/questions/14654758/google-places-api-request-denied-for-android-autocomplete-even-with-the-right-a for more info.

**Comment by schan93** [comment]
I'm having the same issue. 

@swennemans I looked at the link provided and I removed the iOS key I created and made a Browser key. Then I inserted that API key given in place of the previous iOS key I had and I get the same issue. Do you mind going into more details on how to fix this issue?

EDIT: nevermind fixed it. You just need to download the Google Places API for Web to do this. Thanks!

**Comment by watsonbox** [comment]
@PhaelIshall Hopefully you've resolved your issue.  I'll re-open this if not but it doesn't sound like a problem with the library.

**Comment by PhaelIshall** [comment]
it was a problem with the API, you have to access it through the web services API not the iOS for some reason. Please say that in your description.
