### ISSUE TITLE
placeViewClosed keeps the view to reappear

### ISSUE THREAD

**Issue by KarimFikani** [watsonbox/ios_google_places_autocomplete#23]
Every time I tap on the 'X' button the view shows up again because "presentViewController(gpaViewController, animated: false, completion: nil)" is in "viewDidAppear". So every time "dismissViewControllerAnimated(true, completion: nil)" is called the same view controller loads again.

How can I make it jump to a new ViewController?

**Comment by watsonbox** [comment]
Maybe take a look at [this issue](https://github.com/watsonbox/ios_google_places_autocomplete/issues/2).  I just use `viewDidAppear` in the example for convenience but you could call `presentViewController` anywhere.
