### ISSUE TITLE
Separate UI from service layer

### ISSUE THREAD

**Issue by samscam** [watsonbox/ios_google_places_autocomplete#24]
I've had a fork on the go [(samscam/ios_google_places_autocomplete)](http://github.com/samscam/ios_google_places_autocomplete) for a while where I've done quite a bit of work on it. Using it in production on [Knocker](http://knockerapp.com).

I'll clean up what I've done and submit a bunch of pull requests for you for the smaller things, but the big one is that I needed to separate out the UI from the service layer so it can be used in programatic contexts. I've tried to do it in as non-breaking a way I could but would love to go a bit deeper. Would you be game for that?

**Comment by watsonbox** [comment]
Thanks for taking the time to think about contributing this back, and yes this sounds entirely sensible.  I'm sure there are others with a similar use case.
