### ISSUE TITLE
Potential Feature: Use Places Details API to get additional meta-data for a place

### ISSUE THREAD

**Issue by h0h0h0** [watsonbox/ios_google_places_autocomplete#5]
Wanted to check in and see if you thought this was a worthy feature for this.

I would love to get the lat and long of the place as well as a few other points of Meta Data.   However, the Places Autocomplete API does not provide that.  I would make a call to the Places Details API for that.

Would you accept a pull request with that feature that lets you turn that "Details" data on and off?

**Comment by watsonbox** [comment]
Yep sounds good. I actually have some code which does a similar thing that I could add next week, but if you'd like to submit an implementation yourself please do. I think this extra behavior would need some unit tests too.

**Comment by h0h0h0** [comment]
If you pass me your code or drop it Ina branch I could potentially contribute a unit test or two!

**Comment by watsonbox** [comment]
Sure I'll take a look next week.
