### ISSUE TITLE
Have to use pod 'GooglePlacesAutocomplete', :head in my podfile to get the new versions

### ISSUE THREAD

**Issue by thekie** [watsonbox/ios_google_places_autocomplete#6]
The podspec version of the pod is still 0.1 and I had to add :head to my GooglePlacesAutocomplete pod file entry to get the fixed places id and the paces detail functionality.

**Comment by watsonbox** [comment]
That's because I haven't released the next version yet but I will do shortly.

**Comment by watsonbox** [comment]
Version 0.2.0 released.
