### ISSUE TITLE
Errors on Xcode 6.3

### ISSUE THREAD

**Issue by josephkandi** [watsonbox/ios_google_places_autocomplete#7]
The library does not compile on XCode 6.3 with the error AnyObject? is not convertible to String. There are simple fixes though.

**Comment by watsonbox** [comment]
Thanks for pointing this out - I'll update the library to be Swift 1.2 compatible soon.

**Comment by jormon** [comment]
+1

**Comment by jormon** [comment]
I'm running into this issue as well. Can I be of help?

**Comment by watsonbox** [comment]
Thanks for the PR.  I've merged this into the [swift-1.2](https://github.com/watsonbox/ios_google_places_autocomplete/tree/swift-1.2) branch.  The reason being that Travis CI still doesn't [support Xcode 6.3](https://github.com/travis-ci/travis-ci/issues/3216), and I'd like the master branch to remain under CI testing.  It seems that they plan to resolve this soon, at which point I'll merge the changes into master.

Could others possibly confirm that these changes are working?  Then I'll update the README.md to point people using Swift 1.2 in the right direction.

**Comment by watsonbox** [comment]
See also http://blog.travis-ci.com/2015-04-20-state-of-the-mac-infrastructure-on-travis-ci/

**Comment by seenickcode** [comment]
+1 to merge into master

**Comment by watsonbox** [comment]
Trivis CI now [supports](http://blog.travis-ci.com/2015-05-26-xcode-63-beta-general-availability/) XCode 6.3 / Swift 1.2 so I've just released version 0.3.0 which is compatible.
